export const USER_CREATE_REVIEW_REQUEST = "USER_CREATE_REVIEW_REQUEST";
export const USER_CREATE_REVIEW_SUCCESS = "USER_CREATE_REVIEW_SUCCESS";
export const USER_CREATE_REVIEW_FAIL = "USER_CREATE_REVIEW_FAIL";
export const USER_CREATE_REVIEW_RESET = "USER_CREATE_REVIEW_RESET";
